### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mingfang618** [chr1swallace/GUESSFM#10]
I am trying to applied the package  "GUESS" for my analysis, but it produces some errors "package ‘ggbio’ is not available (for R version 3.2.3)" when installing the package. May I know what kind of R version should I use?

Further, is the package based on Windows system or Linux system?

Thank you!

**Comment by chr1swallace** [comment]
ggbio is a Bioconductor package, so the problem is not your R version, but my Readme which should say:

```
source("https://bioconductor.org/biocLite.R")
biocLite("ggbio")
```

Thanks for the note, I will correct.

GUESSFM is an R package, and is platform agnostic, but depends on GUESS which you need to install according to the instructions at http://www.bgx.org.uk/software/guess.html.

**Comment by mingfang618** [comment]
Thank you, finally it works. It seemed R2GUESS has many depandencis, but I installed them anyway.
